package hibnetonetomany.mapping;
// Generated Dec 18, 2014 12:15:06 AM by Hibernate Tools 4.3.1



/**
 * Certificate generated by hbm2java
 */
public class Certificate  implements java.io.Serializable {


     private int id;
     private Employee employee;
     private String certificateType;
     private String certificateName;

    public Certificate() {
    }


    public Certificate(String certificateName) {
       this.certificateName = certificateName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getCertificateType() {
        return this.certificateType;
    }
    
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType;
    }
    public String getCertificateName() {
        return this.certificateName;
    }
    
    public void setCertificateName(String certificateName) {
        this.certificateName = certificateName;
    }

}


